# .github/workflows/ci.yml
name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodni klonlash
      uses: actions/checkout@v3

    - name: Node.js o'rnatish
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Paketlarni o'rnatish
      run: npm install

    - name: Testlarni ishga tushirish
      run: npm test
